<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\User' . "\0" . 'id', '' . "\0" . 'App\\Entity\\User' . "\0" . 'email', '' . "\0" . 'App\\Entity\\User' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\User' . "\0" . 'password', '' . "\0" . 'App\\Entity\\User' . "\0" . 'firstname', '' . "\0" . 'App\\Entity\\User' . "\0" . 'lastname', '' . "\0" . 'App\\Entity\\User' . "\0" . 'address', '' . "\0" . 'App\\Entity\\User' . "\0" . 'tel', '' . "\0" . 'App\\Entity\\User' . "\0" . 'compname', '' . "\0" . 'App\\Entity\\User' . "\0" . 'picture', '' . "\0" . 'App\\Entity\\User' . "\0" . 'annonces', '' . "\0" . 'App\\Entity\\User' . "\0" . 'candidatures', '' . "\0" . 'App\\Entity\\User' . "\0" . 'signals', '' . "\0" . 'App\\Entity\\User' . "\0" . 'aboutme', '' . "\0" . 'App\\Entity\\User' . "\0" . 'profSkills', '' . "\0" . 'App\\Entity\\User' . "\0" . 'workExps', '' . "\0" . 'App\\Entity\\User' . "\0" . 'education', '' . "\0" . 'App\\Entity\\User' . "\0" . 'languageProfs', '' . "\0" . 'App\\Entity\\User' . "\0" . 'sex', '' . "\0" . 'App\\Entity\\User' . "\0" . 'birthdate', '' . "\0" . 'App\\Entity\\User' . "\0" . 'nationality', '' . "\0" . 'App\\Entity\\User' . "\0" . 'socialMedia', '' . "\0" . 'App\\Entity\\User' . "\0" . 'cvFilename', '' . "\0" . 'App\\Entity\\User' . "\0" . 'coverLetterFilename', '' . "\0" . 'App\\Entity\\User' . "\0" . 'isActive'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\User' . "\0" . 'id', '' . "\0" . 'App\\Entity\\User' . "\0" . 'email', '' . "\0" . 'App\\Entity\\User' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\User' . "\0" . 'password', '' . "\0" . 'App\\Entity\\User' . "\0" . 'firstname', '' . "\0" . 'App\\Entity\\User' . "\0" . 'lastname', '' . "\0" . 'App\\Entity\\User' . "\0" . 'address', '' . "\0" . 'App\\Entity\\User' . "\0" . 'tel', '' . "\0" . 'App\\Entity\\User' . "\0" . 'compname', '' . "\0" . 'App\\Entity\\User' . "\0" . 'picture', '' . "\0" . 'App\\Entity\\User' . "\0" . 'annonces', '' . "\0" . 'App\\Entity\\User' . "\0" . 'candidatures', '' . "\0" . 'App\\Entity\\User' . "\0" . 'signals', '' . "\0" . 'App\\Entity\\User' . "\0" . 'aboutme', '' . "\0" . 'App\\Entity\\User' . "\0" . 'profSkills', '' . "\0" . 'App\\Entity\\User' . "\0" . 'workExps', '' . "\0" . 'App\\Entity\\User' . "\0" . 'education', '' . "\0" . 'App\\Entity\\User' . "\0" . 'languageProfs', '' . "\0" . 'App\\Entity\\User' . "\0" . 'sex', '' . "\0" . 'App\\Entity\\User' . "\0" . 'birthdate', '' . "\0" . 'App\\Entity\\User' . "\0" . 'nationality', '' . "\0" . 'App\\Entity\\User' . "\0" . 'socialMedia', '' . "\0" . 'App\\Entity\\User' . "\0" . 'cvFilename', '' . "\0" . 'App\\Entity\\User' . "\0" . 'coverLetterFilename', '' . "\0" . 'App\\Entity\\User' . "\0" . 'isActive'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', []);

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname(?string $firstname): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', [$firstname]);

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastname(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastname', []);

        return parent::getLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastname(?string $lastname): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastname', [$lastname]);

        return parent::setLastname($lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(?string $address): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', []);

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel(?string $tel): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', [$tel]);

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompname(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompname', []);

        return parent::getCompname();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompname(?string $compname): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompname', [$compname]);

        return parent::setCompname($compname);
    }

    /**
     * {@inheritDoc}
     */
    public function getPicture(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPicture', []);

        return parent::getPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setPicture(?string $picture): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPicture', [$picture]);

        return parent::setPicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnonces(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnonces', []);

        return parent::getAnnonces();
    }

    /**
     * {@inheritDoc}
     */
    public function addAnnonce(\App\Entity\Annonce $annonce): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAnnonce', [$annonce]);

        return parent::addAnnonce($annonce);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAnnonce(\App\Entity\Annonce $annonce): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAnnonce', [$annonce]);

        return parent::removeAnnonce($annonce);
    }

    /**
     * {@inheritDoc}
     */
    public function getCandidatures(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCandidatures', []);

        return parent::getCandidatures();
    }

    /**
     * {@inheritDoc}
     */
    public function addCandidature(\App\Entity\Candidature $candidature): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCandidature', [$candidature]);

        return parent::addCandidature($candidature);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCandidature(\App\Entity\Candidature $candidature): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCandidature', [$candidature]);

        return parent::removeCandidature($candidature);
    }

    /**
     * {@inheritDoc}
     */
    public function getSignals(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignals', []);

        return parent::getSignals();
    }

    /**
     * {@inheritDoc}
     */
    public function addSignal(\App\Entity\Signal $signal): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSignal', [$signal]);

        return parent::addSignal($signal);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSignal(\App\Entity\Signal $signal): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSignal', [$signal]);

        return parent::removeSignal($signal);
    }

    /**
     * {@inheritDoc}
     */
    public function getAboutme(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAboutme', []);

        return parent::getAboutme();
    }

    /**
     * {@inheritDoc}
     */
    public function setAboutme(?string $aboutme): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAboutme', [$aboutme]);

        return parent::setAboutme($aboutme);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfSkills(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfSkills', []);

        return parent::getProfSkills();
    }

    /**
     * {@inheritDoc}
     */
    public function addProfSkill(\App\Entity\ProfSkill $profSkill): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProfSkill', [$profSkill]);

        return parent::addProfSkill($profSkill);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProfSkill(\App\Entity\ProfSkill $profSkill): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProfSkill', [$profSkill]);

        return parent::removeProfSkill($profSkill);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkExps(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkExps', []);

        return parent::getWorkExps();
    }

    /**
     * {@inheritDoc}
     */
    public function addWorkExp(\App\Entity\WorkExp $workExp): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addWorkExp', [$workExp]);

        return parent::addWorkExp($workExp);
    }

    /**
     * {@inheritDoc}
     */
    public function removeWorkExp(\App\Entity\WorkExp $workExp): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeWorkExp', [$workExp]);

        return parent::removeWorkExp($workExp);
    }

    /**
     * {@inheritDoc}
     */
    public function getEducation(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEducation', []);

        return parent::getEducation();
    }

    /**
     * {@inheritDoc}
     */
    public function addEducation(\App\Entity\Education $education): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEducation', [$education]);

        return parent::addEducation($education);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEducation(\App\Entity\Education $education): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEducation', [$education]);

        return parent::removeEducation($education);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguageProfs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguageProfs', []);

        return parent::getLanguageProfs();
    }

    /**
     * {@inheritDoc}
     */
    public function addLanguageProf(\App\Entity\LanguageProf $languageProf): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLanguageProf', [$languageProf]);

        return parent::addLanguageProf($languageProf);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLanguageProf(\App\Entity\LanguageProf $languageProf): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLanguageProf', [$languageProf]);

        return parent::removeLanguageProf($languageProf);
    }

    /**
     * {@inheritDoc}
     */
    public function getSex(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSex', []);

        return parent::getSex();
    }

    /**
     * {@inheritDoc}
     */
    public function setSex(?string $sex): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSex', [$sex]);

        return parent::setSex($sex);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthdate(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthdate', []);

        return parent::getBirthdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthdate(?string $birthdate): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthdate', [$birthdate]);

        return parent::setBirthdate($birthdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getNationality(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNationality', []);

        return parent::getNationality();
    }

    /**
     * {@inheritDoc}
     */
    public function setNationality(?string $nationality): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNationality', [$nationality]);

        return parent::setNationality($nationality);
    }

    /**
     * {@inheritDoc}
     */
    public function getSocialMedia(): ?\App\Entity\SocialMedia
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSocialMedia', []);

        return parent::getSocialMedia();
    }

    /**
     * {@inheritDoc}
     */
    public function setSocialMedia(\App\Entity\SocialMedia $socialMedia): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSocialMedia', [$socialMedia]);

        return parent::setSocialMedia($socialMedia);
    }

    /**
     * {@inheritDoc}
     */
    public function getCvFilename(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCvFilename', []);

        return parent::getCvFilename();
    }

    /**
     * {@inheritDoc}
     */
    public function setCvFilename(?string $cvFilename): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCvFilename', [$cvFilename]);

        return parent::setCvFilename($cvFilename);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoverLetterFilename(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoverLetterFilename', []);

        return parent::getCoverLetterFilename();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoverLetterFilename(?string $coverLetterFilename): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoverLetterFilename', [$coverLetterFilename]);

        return parent::setCoverLetterFilename($coverLetterFilename);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', []);

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive(bool $isActive): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        return parent::setIsActive($isActive);
    }

}
