<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPVrefyj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPVrefyj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPVrefyj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPVrefyj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPVrefyj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PVrefyj',
    'container.build_id' => '2da42bfc',
    'container.build_time' => 1646133529,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPVrefyj');
